apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: adilsonsilvajr/diabetes-app:latest
          resources:
            requests:
              memory: "1G"
            limits:
              memory: "2G"
          securityContext:
            privileged: true
          ports:
            - containerPort: 8501