FROM python:3.9

RUN mkdir ml

WORKDIR /ml

COPY model model

COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY diabetes_ML.py diabetes_ML.py

COPY ./start.sh ./start.sh

RUN chmod +x start.sh

EXPOSE 80

ENTRYPOINT ["./start.sh", "start"]
